### ISSUE TITLE
Restructure the "Community" section

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1874]
To improve site navigation, the following changes will be made to the "Community" section:

- [x] Update the "Overview"
- [x] Apply the `docs` layout to use and show a left nav pane
- [x] Move the "[Contributing](https://knative.dev/contributing/)" into the "[Community](https://knative.dev/community/)" section below the "[Code Samples](https://knative.dev/community/samples/)" (https://github.com/knative/website/issues/51)
  - [x] https://github.com/knative/community/pull/45 - Fix and ensure all files include the required frontmatter, including [feature tracks](https://knative.dev/contributing/mechanics/feature-tracks/)
- [x] Implement redirects for all moved files/URLs in that file's frontmatter (#1925)
- [x] Add "build-time" logic to convert fully qualified URLs in topic from the knative/community repo, to relative URLs within the built content for knative.dev. (https://github.com/knative/community/issues/3)
- [ ] ~~Author "how to contribute to docs" instructions (add the missing Hugo/Docsy/site requirements and "how tos")~~ (See draft in https://github.com/knative/docs/issues/1917)

[View the proposed structure](https://docs.google.com/spreadsheets/d/1L3EAeTX7RRdZhcQZeNmxwN4DCncuImCXA5A1_KQvwSk/edit?ts=5d826691#gid=413198505&range=206:206)
