### ISSUE TITLE
New "Cluster maintenance" section

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1895]
Create an operator focused section that covers how to maintain a cluster running Knative (post install information about how to add or remove features, as well as how to upgrade).

- [ ] Repurpose the 'custom install' topic to align with the how to "maintain your cluster"
  - include mention (and/or links to):
     - 'kn' CLI
     - networking
     - observerability

  - [ ] install new features/plugins
  - [ ] remove features/plugins
  - [ ] split out reference information (and then link to it from here): #1896
  
- [ ] Provide an overview of the process of "upgrading" the components and features/plugins that you have running on your cluster (#130)
  - describe the process (ie. upgrade one thing, test it, then move on to the next thing)
  - provide an example (flow, commands, and how to specify manifest files)
  - include how to verify "upgraded" component/feature/plugin
  - the Serving and Eventing sections should each include their own "upgrading" topic, which you link to from here (to avoid duplication)

- For all moved or renamed files, add a redirect to that file's frontmatter (#1925)

[View navigation proposal/mock](https://docs.google.com/spreadsheets/d/1L3EAeTX7RRdZhcQZeNmxwN4DCncuImCXA5A1_KQvwSk/edit?ts=5d826691#gid=413198505&range=181:181)

**Comment by grzesiek** [comment]
I believe that being able to easily upgrade Knative is really important. It is not clear how to do that without a large downtime at the moment.

**Comment by abrennan89** [comment]
@houshengbo is this issue related to any of the operator docs work you've been doing?

**Comment by abrennan89** [comment]
I think we can close this issue now since it's sort of covered by the following:

- Observability docs https://github.com/knative/docs/issues/2931
- Plugins https://github.com/knative/docs/issues/3534
- Reference docs https://github.com/knative/docs/pull/3334
- Upgrading docs https://dev-knative.netlify.app/development/admin/upgrade/

I think if there is anything missing let's open a new, smaller issue for it.
