### ISSUE TITLE
Update the "Install" section to cover "Install options"

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1898]
The install details for either the Serving or Eventing component are to be separated into their individual sections. This provides users the specific details about only the Knative component they are interested.

With the above model, the top-level "Install" section should be repurposed to provide an overview, the available install options, and enough detail to help the user choose the desired install path.

The following changes need to be made:

- [x] For all moved or renamed files, add a redirect to that file's frontmatter (#1925)
- [ ] Rename section to "Install options"
- [ ] Direct users to the Serving or Eventing specific instructions
       - Mention that those instructions require a pre-existing cluster ("component specific instructions that you can use to install Knative on any Kubernetes cluster")
       - "If you want to install xyz, then see the instructions at...."
- [ ] Edit:
       Clearly state the available install options: 
        - Ensure both components are equally discussed (currently only mentions serving) 
        - (1) See Serving (includes installing 'kn')
        - (2) See Eventing (includes installing 'kn')
        - (3) Or See one of the following guide if you want to install locally or on one of the following hosts (community contributed host specific guides)
        Mention and link to:
        - ['kn' CLI](https://github.com/knative/client/blob/master/docs/README.md) (install and use it to.......)
        - "Cluster maintenance" section (if you want to modify your installation or upgrade, see ....)
- [ ] Create a sub-section "Installing locally or on hosted clusters"
     - [ ] Move the "local" and "hosted" install guides here
     - [ ] Explain/mention that they "help you quickly install both Serving and Eventing in the specified environment or hosted cluster"
- [ ] Move/repurpose the "install on existing cluster" into separate Serving and Eventing specific instructions

**Comment by samodell** [comment]
Newer plan: https://github.com/knative/docs/issues/2137

If we move forward with the plan outlined there, I'll close this out.

**Comment by RichieEscarez** [comment]
Reopening for now but we need revisit this since it doesn't look like all of these were addressed in #2137
