### ISSUE TITLE
New  "how to contribute to docs" instructions

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1917]
Need to author the instructions about how to contribute to knative.dev, including all the missing Hugo/Docsy/site requirements. When and where to add:
- [ ] General info about site:
       - Hugo
       - Docsy
       - [Markdown processor info](https://gohugo.io/getting-started/configuration-markup/)
       - Netlify
       - knative/website repo

- [ ] front matter

    ```
    ---
    title: “The file’s title (do not include another H1 title in the body).”
    linkTitle: “optional short title”
    weight: 10
    type: “docs”
    ---
    ```

     - ‘title’ and ‘type: “docs”’ are required. 
     - ‘weight’ is also required and allows you to defined
    where that element shows relative to other content in the Nav tree (otherwise elements are 
    alphabetical). More info: https://gohugo.io/content-management/front-matter/#predefined
     - ‘linkTitle’ is optional and allows you to provide an 
    alternative (shorter) title for the Nav tree. 
  
- [ ] Redirect URLs for moved and renamed source files (add `aliases` to frontmatter): https://github.com/knative/docs/issues/1925
- [ ] Dynamic variables. Use them to reduce release maintenance and ensure content accuracy. The following variable are dynamically populated based on the URL of the content in knative.dev:
   - [ ] add the corresponding branchname by using the `{{< branch >}}` variable ([shortcode](https://github.com/knative/website/blob/master/layouts/shortcodes/branch.md))
   - [ ] add the corresponding version number by using the `{{< version >}}` variable ([shortcode](https://github.com/knative/website/blob/master/layouts/shortcodes/version.md))

    See examples in the [smoketest page](https://knative.dev/smoketest/)
   
- [ ] SEO (filename (no capital letters, no product names), titles (sentence case), cross links)
- [ ] Document linking conventions - all ./ are required for "same directory" relative links
- [ ] If there is more than a single .md file in a sub folder, then that folder must include and use an `_index.md` (to define that "[section](https://gohugo.io/content-management/sections/)").

   (ie. need to mention that if you want to add that 
   second file to a folder, then you must also add (create) the required 
   "section definition" (using an `_index.md` file).
- [ ] Using shortcodes:
   - [ ] Optional: Add the following to the frontmatter of a file to show/hide an in-page TOC (uses the ["landingtoc" partial](https://github.com/knative/website/blob/master/layouts/partials/landingtoc.html))
           By default, the in-page TOC shows in empty/blank _index.md section files to list all the sub-topics in that section.
            - add `showlandingtoc: "true"` to add the in-page TOC
            - add `showlandingtoc: "false"` to prevent the in-page TOC from showing on a blank page or non `docs` type page (for example, a page in the /community section)
   - [ ] Nested shortcodes are NOT supported - results in mixed content (.md + HTML) in the markdown that gets processed to HTML (so code (ie HTML or Markdown) is rendered (not just text)) 
   - [ ] [`{{% readfile file="FILENAME.md" %}}` shortcode](https://github.com/knative/website/blob/master/layouts/shortcodes/readfile.md):
 
      - [ ] In the blank _index.md pages that can automatically generate and render an in-page nav tree. Make clear which files are "included" and rendered on the site using the `readfile` shortcode.
        ie. add a comment in the included file
        ```
        <!-- This file is rendered in knative.dev using the "readfile" shortcode. 
        See the _index.md file in this directory. -->
        ```

      - [ ] Dynamically add code: `{{< readfile file="code-written-in.go" code="true" lang="go" >}}`

         See examples in the [smoketest page](https://knative.dev/smoketest/)

- [ ] How to build knative.dev locally: Run [`https://github.com/knative/website/blob/master/scripts/localbuild.sh`](https://github.com/knative/website/blob/master/scripts/localbuild.sh)

Other "docs contributor" related items:

- [ ] https://github.com/knative/docs/issues/1032
- [ ] https://github.com/knative/docs/issues/1009
- [ ] https://github.com/knative/docs/issues/1282
- [ ] https://github.com/knative/docs/issues/1239
- [ ] https://github.com/knative/docs/issues/1344

**Comment by RichieEscarez** [comment]
Two items remain:

- [ ] Nested shortcodes are NOT supported - results in mixed content (.md + HTML) in the markdown that gets processed to HTML (so code (ie HTML or Markdown) is rendered (not just text)) (today, this is mentioned only here https://github.com/knative/website/blob/main/layouts/shortcodes/readfile.md)
- [ ]  How Prow chooses reviewers: https://github.com/kubernetes/test-infra/tree/master/prow/plugins/approve/approvers#blunderbuss-selection-mechanism

**Comment by abrennan89** [comment]
I think it's safe to close this now since we've moved to mkdocs. Anything left to be added should probably just be opened as a new task. I don't think prow auto-selects reviewers anymore anyway.
