### ISSUE TITLE
Restructure "Serving component" section

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#1922]
Align content with the developer flow and arrange content into logical sections.

[View proposed nav structure](https://docs.google.com/spreadsheets/d/1L3EAeTX7RRdZhcQZeNmxwN4DCncuImCXA5A1_KQvwSk/edit?ts=5d826691#gid=413198505&range=32:32)

- [x] For all moved or renamed files, add a redirect to that file's frontmatter (#1925)
- [ ] Add ‘kn’ CLI to the Getting Started
- [ ] Create a Serving only install section
- [ ] Create new “Deploying apps” section
- [ ] Organize “Scaling” content into new section
- [ ] Organize “Networking” content into new section
- [ ] Organize “Debugging (and Observabiltiy)” content into new section
- [ ] Create new “Serving concepts” section

**Comment by abrennan89** [comment]
@carieshmarie I think each of the checkbox items on this issue could probably be an epic of its own instead, with its own subtasks. Otherwise the scope is too overwhelming I think :slightly_smiling_face:
