### ISSUE TITLE
Update docs to include changes related to Multi Tenant channel based broker

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#2345]
## What is changing? (Please include as many details as possible.)

As of 0.14, MT channel based broker will be introduced
https://knative.dev/development/eventing/mt-channel-based-broker/

## How will this impact our users?
Knative will now provide a Multi Tenant Broker implementation that uses Channels for event routing. 

## In what release will this take happen (to the best of your knowledge)?
0.14

## Context
Link to associated PRs or issues from other repos here.

1. https://github.com/knative/docs/pull/2321 previous work done by @vaikas 
2. Doc with context: https://docs.google.com/document/d/1qYnmkRduWLUFQ3vEsaw7jU_mxS_nDHHkDkcGRf1_Fy4/edit#heading=h.ra3is5gwyzel

## Additional info
Requirements for docs are as follows:

1. Going through the other docs to see what needs to be revised in light of the MT broker.
2. Going over the MT broker docs with a tech writer eye.

**Comment by abrennan89** [comment]
**To do list**

- [ ] Create Brokers subsection to group information
  - [ ] Create issue to split out broker and trigger docs https://knative.dev/docs/eventing/broker-trigger/ instead give these their own section and group broker information.
- [ ] Side quest - can we get some better formatting for notes in the docs site @evankanderson ? I see a lot of "NOTE:" and it doesn't do much to highlight anything. Something simple by importance would do, e.g. https://www.w3schools.com/howto/howto_css_notes.asp
- [ ] Create user stories for different channel types and confirm what we support for each broker. Open an issue to improve channel docs generally, e.g. https://knative.dev/docs/eventing/channels/channels-crds/
- [ ] Create issue to make a central CRD reference section for serving and eventing that we can include or link to (reuse) for a central reference for things like configmaps [needs more thought]

**Comment by abrennan89** [comment]
#2349 awaiting review to close this
