### ISSUE TITLE
Knative Samples: Add alternative version with using "kn"

### ISSUE THREAD

**Issue by rhuss** [knative/docs#2435]
**Describe the change you'd like to see**

For samples that include YAML descriptors of Knative resources, I suggest adding a corresponding `kn` command in an additional TAB, like it is done for the various autoscale options in https://knative.dev/development/serving/configuring-autoscaling/

In the first step, all relevant sections should be identified and then the alternative `kn` syntax added. It is to be discussed which variant should be the default (e.g. in the first tab): The YAML representation or the `kn` syntax.

**Additional context**

The Knative client [kn](https://github.com/knative/client) supports ~ 90% of the Knative Serving functionality and the basic Knative Eventing elements like built-in sources and triggers. For the supported features, it makes sense to give the user both alternatives as choices.

**Comment by abrennan89** [comment]
@rhuss do you want to add a list of commands here and we can split this into smaller tasks? I can add some of it when I'm doing docs PRs anyway.

**Comment by rhuss** [comment]
Sorry, I'm still behind. The plan was first to identify on which pages a in sample alternative could be added and then group this into smaller tickets. This analysis hasn't happened yet. If you stumble upon a page with a yaml example it would be cool to add a reference to this page to this issue. Next week we should be more clear how to proceed.

**Comment by abrennan89** [comment]
Can do!

**Comment by abrennan89** [comment]
List of pages that need `kn` examples added:
- [ ] [Deploying apps](https://knative.dev/development/serving/getting-started-knative-app/)
- [ ] [routing blue green deployment traffic](https://knative.dev/development/serving/samples/blue-green-deployment/)
- [ ] [Autoscaling](https://knative.dev/development/serving/configuring-autoscaling/) I'd wait til after I merge #2439 though
- [ ] [event source docs](https://knative.dev/development/eventing/samples/kubernetes-event-source/) seems to be specifically apiserversource, page could maybe do with other updates as well
- [ ] [Event registry docs](https://knative.dev/development/eventing/event-registry/)
- [ ] Probably a lot of the [code samples](https://knative.dev/development/eventing/samples/) but IDK if you're scoping those or just the main docs?

I'll stop there for now maybe in case we get overwhelmed.
Let's try to cross some of these off the list as a first batch and then we can identify which are next?

**Comment by rhuss** [comment]
Cool, thanks ! Let's start with the "Getting started" guide and add a corresponding kn example. I will do a PR for this now.

**Comment by rhuss** [comment]
@abrennan89 I submitted a first PR for the "Getting Started" experience with `kn`: #2514

**Comment by abrennan89** [comment]
Added an issue for blue/green deployment, taking it off the list to track elsewhere: https://github.com/knative/docs/issues/3349

**Comment by abrennan89** [comment]
Added an issue for APIServerSource docs cleanup, taking it off the list to track elsewhere: https://github.com/knative/docs/issues/3351

**Comment by abrennan89** [comment]
Added an issue for event registry docs cleanup, taking it off the list to track elsewhere: https://github.com/knative/docs/issues/3352

**Comment by abrennan89** [comment]
Marking the code samples off the list because we need to go through them and figure out what needs to be updated and this should be part of the Epic work for https://github.com/knative/docs/issues/3346

**Comment by abrennan89** [comment]
I have created an Epic to track this issue instead #3346 - closing this issue but have retained the context in the new Epic to make sure it's tracked.
Please add any YAML examples that need kn CLI commands to the new Epic. You may need permissions / zenhub but if you have any trouble please ping me on Slack.
