### ISSUE TITLE
Split out broker and trigger docs

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#2554]
**Describe the change you'd like to see**

- [x] Break out broker and trigger docs into their own sections
- [x] Update broker docs to remove default broker, this is now MT broker
- [x] General cleanup of broker and trigger user stories

**Additional context**
Follow up comments from #2349 
cc @vaikas

**Comment by abrennan89** [comment]
Notes from Slack:
As of 0.16, `default` broker is deprecated and we use MT broker by default.
Currently only InMemoryChannel persistence store; Kafka landing when?
Source, channel and broker components.

**Comment by vaikas** [comment]
Kafka channel should be out there, v1alpha1? I thought v1beta1 went out but maybe not released? @slinkydeveloper @matzew  probably have more details on this.

**Comment by abrennan89** [comment]
I meant specifically v1beta1 I think but this afaik went into 0.16 so I think we're cool, was just thinking out loud :slightly_smiling_face:
