### ISSUE TITLE
Consolidate docs authoring, website, and maintainer info

### ISSUE THREAD

**Issue by RichieEscarez** [knative/docs#2960]
## What is changing? 

Docs contributor docs were previously all in the knative/community repo, under the /docs folder (which had "docs owners" special access). Today, there are chunks of contributing, authoring, and website info across the /doc, /website/ and /community repos.

To make contributor and maintainer info accessible and discoverable, we should create a section in the website that functions as a consolidated single source for all this info (a new "/help" section in the site):

`https://knative.dev/`**`help/`**

## How will this impact our users?

They will find what they are looking for and become fully independent docs contributors.

Design:

- Unlike the existing "Documentation" "Blog" and "Community" sections, the new "Help" section will not be exposed in the main website navigation.
- The `/help/` section will have independent sections for:
   - "Help docs" - include page elements (ie. hugo, docsy, etc), required page and site frontmatter, blog info
      - https://github.com/knative/docs/issues/1917
   - "Maintaining docs" - how to: (1) update the API docs (2) create a new docs version/branch, (3) release and publish a version
      - https://github.com/knative/website/issues/39
   - "Docs publishing" - how the site works, knative specific customizations, how to use hugo/docsy/netlify, regular maintenance tasks
       - https://github.com/knative/docs/issues/2668
- The content under the `/help` section will be strategically linked to from the main entry points for contributors
  - PR templates will include links to corresponding `/help/how to do this` topics
  - README.md, CONTRIBUTING.md, DEVELOPMENT.md, and others will link to the `/help` content (redirect all to this single source for all things docs)
- knative/community will continue to be the home for Knative member/contributor type info, AND crosslink between `/help` content

## In what release will this take happen (to the best of your knowledge)?
 v.next

## Context
- https://knative.dev/community/contributing/docs/docs-contributing/ (https://github.com/knative/community/tree/master/docs)
- https://github.com/knative/docs/blob/master/README.md
- https://github.com/knative/docs/blob/master/CONTRIBUTING.md
- https://github.com/knative/docs/blob/master/new-page-template.md
- https://github.com/knative/website/blob/master/DEVELOPMENT.md
- https://github.com/knative/website/blob/master/scripts/build.sh
- https://github.com/knative/website/blob/master/scripts/localbuild.sh
- https://github.com/knative/docs/tree/master/blog

## TODOs

- [x] (https://github.com/knative/docs/pull/3437) Move all information into a `/help` folder in the knative/docs repo 
       (URL: `https://github.com/knative/docs/tree/main/help`)
  - [x] (https://github.com/knative/docs/pull/3437) knative/docs repo
  - [x] ()https://github.com/knative/community/pull/557 knative/community repo
  - [x] Make sure "repo only" files are excluded from the Site build (ex. https://knative.dev/contributing/)

- [x] Add/replace existing README.md, CONTRIBUTING.md, and DEVELOPMENT.md content with links to these new "docs contributor how-to guidelines"
   - [x] (https://github.com/knative/docs/pull/3437) knative/docs repo
   - [x] (https://github.com/knative/community/pull/557) knative/community repo

- [x] (https://github.com/knative/docs/pull/3437) Consolidate and fix "docs" and "blog" GitHub templates for PRs https://github.com/knative/docs/pull/3341
   - [x] (https://github.com/knative/website/pull/288) Add links within the templates to point to these new "docs contributor how-to guidelines" https://github.com/knative/community/pull/531

- [x] (https://github.com/knative/website/pull/288) knative/website repo
   - Add new `help` section to the knative.dev site/build
   - Add "Help" links next to GitHub links in the right-hand side bar 
![image](https://user-images.githubusercontent.com/11762685/97363163-63c8dd00-185f-11eb-9719-f2a5be39ef06.png)

- [ ] Instructions for website:
  - [ ] (https://github.com/knative/docs/pull/3437 - incomplete draft) publishing
  - [ ] (https://github.com/knative/docs/pull/3437 - incomplete draft) maintenance
  - [ ] (https://github.com/knative/docs/pull/3437 - incomplete draft) docs release process

**Comment by RichieEscarez** [comment]
Current state (running locally):

![image](https://user-images.githubusercontent.com/11762685/97360823-ee0f4200-185b-11eb-84e0-ebe0ca30c4a6.png)

**Comment by abrennan89** [comment]
Thanks for taking on the blog stuff with all of this @RichieEscarez !
Do you think we could set some preliminary dates / milestones for completing aspects of this work? Is it long term stuff that should be added to the roadmap for this year?

**Comment by omerbensaadon** [comment]
@RichieEscarez moved this to backlog since looks like you're currently working on it. 

It's also in the [EPIC] Clean Up the Cruft as "in progress"

Keep me posted if you want me to split out some of this stuff as separate issues?

**Comment by RichieEscarez** [comment]
Made a little progress on this:
![image](https://user-images.githubusercontent.com/11762685/110196585-5d90d180-7dfa-11eb-93f4-ad59f0547009.png)

**Comment by omerbensaadon** [comment]
PS: @RichieEscarez I would push that with some //TODOs, doesn't have to be perfect 👍🏼  

PS: If you want to work on it solo I would still push and just put //TODO @RichieEscarez

**Comment by RichieEscarez** [comment]
> @RichieEscarez I would push that with some //TODOs, doesn't have to be perfect 👍🏼
> 
> PS: If you want to work on it solo I would still push and just put //TODO @RichieEscarez

Yes, thats the plan. Thanks Omer! I almost got it to a state to push but I ran out of time (lots of distractions lately from various request combined with lots of merge conflicts and changes within the files im touching). Generally there are updates across knative/docs, knative/website, and knative/community (since duplicate and outdated info exists throughout), so theres a lot of coordination, testing, and rebasing to be able to consolidate this stuff.

**Comment by omerbensaadon** [comment]
@RichieEscarez ok awesome! 

@snneji @RichardJJG could be good folks to review this since they are fairly new 🥇

**Comment by RichieEscarez** [comment]
Version sent for review (a lot of the "website" section have Todo's):
![image](https://user-images.githubusercontent.com/11762685/113956251-0d7aa580-97d2-11eb-9c0d-e52c92b081fc.png)

**Comment by RichieEscarez** [comment]
Status: A lot of the website info, both publishing and maintainer instructions have been left in draft state given that the team has proposed to replace Hugo and Docsy website build tools

**Comment by RichieEscarez** [comment]
Closing this given that the team has started planning the migration to different site tooling: https://docs.google.com/document/d/1434cyG3bUvjOLD8KtT7Flc96460QpS5PFnCtbpAa5pM/edit#heading=h.n8a530nnrb

All "website" related internal "how-to" documentation will need to change and be updated with the new tooling information.
