### ISSUE TITLE
Automation of docs tasks

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3112]
**Describe the change you'd like to see**

It was discussed a while ago in the Docs WG call that we should determine a list of automated tasks for the repo to make contribution easier. @evankanderson was interested in helping out with the technical parts of this, but we need to give him a list of things we need and priority.

_[WIP] List:_

- [ ] Automated preview links [Issue #] (@RichieEscarez  is already doing work re Netlify previews on this which looks good)
- [ ] Automated tests (AI: let's determine a list of what actually needs to be checked for a successful PR, any gaps, anything we test for but don't really need to) [Issue #] 
- [ ] Automated labels / sorting (AI: revisit our issue templates and see if there's a way we can make these more specific, or auto-detect information that Github can then apply labels for) [Issue #] 
- [ ] Fix the cla-bot. I don't know what the options are here, but it's a pain currently :slightly_smiling_face: [Issue #] 
- [ ] Automatically assigning SMEs for PR reviews. Sort of doing this already, but would be nice if it was more consistently assigning the right people. [Issue #] 

_Not in scope:_

- We will still need a manual triage process; this is being figured out with other WGs / TOC at the moment, and a proposal for consistent processes is in progress.

**Additional context**

Added [Issue #] as a placeholder to make sure any work we do from this list is being tracked somewhere.

**Comment by omerbensaadon** [comment]
I would like to work on this! I'll DM you on Slack and follow back up on this thread once I have more context.

**Comment by abrennan89** [comment]
Issue moved to [knative/ux #38](https://github.com/knative/ux/issues/38) via [**ZenHub**](https://www.zenhub.com/)
