### ISSUE TITLE
[EPIC] Docs infrastructure work

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#3520]
## Expected Behavior

- [ ]  Anyone from the docs team should be able to quickly and easily build and release the latest version of the docs
- [x] There should be documentation templates and guidelines for adding new sections of content and/or pages to the docs, as well as an overall information architecture that can be updated to show where new doc sections will live
- [ ] Docs tasks are automated where possible to reduce load on writers
- TBA

**Comment by omerbensaadon** [comment]
@abrennan89 I may have to move this out of Early Beta as it needs further discussion, I think we've checked off a few of these boxes. We may want to discuss at DUX next week?

**Comment by abrennan89** [comment]
@omerbensaadon I'm not concerned with it for right now, +1 for moving it to late beta

**Comment by abrennan89** [comment]
@csantanapr any update on this one?
