### ISSUE TITLE
[EPIC] MkDocs Migration

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3546]
## Context

This Epic will house the logistics required to combine all of the necessary work to migrate Knative from Hugo to MkDocs.

## How will we know when this Epic is finished?
This Epic will be finished when the Docs Writers and the UX WG members are working on the same branch and that branch is an MkDocs version of the Knative site. 

## Prototype

<img width="1020" alt="Screen Shot 2021-05-10 at 8 54 02 AM" src="https://user-images.githubusercontent.com/16281246/117662181-49a47b80-b16d-11eb-8efc-c416ceff5caa.png">

https://miro.com/app/board/o9J_lGNC-LY=/?moveToWidget=3074457358533575878&cot=14

## Potential Feature List 

- [x] Initial migration from julz/docs/mkdocs to knative/docs/mkdocs
- [x] Migration from knative/docs/mkdocs to knative/docs/main 
- [x] knative/docs/main updated with correct URL Redirects for MkDocs
