### ISSUE TITLE
[EPIC] Beta Homepage Updates 

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3640]
## Description: 
Before we close out Early Beta, we want to make sure we have a homepage we can be proud of shipping publicly. The current homepage looks great, but needs a bit of smoothing out. 

This issue will be an Epic which contains many child issues, but will also contain some Acceptance Criteria which apply to any changed we make. 

If you have [Zenhub](https://www.zenhub.com/) you'll be able to see all of the child issues, or just check which issues reference this one. 

---

## Story
```
As Eli the End User
I want to see a clean, bug-less Knative homepage
So that when I visit Knative.dev it inspires confidence in the project 
```

## Acceptance Criteria
`All browsers`
```
GIVEN I am on my PC in any major web browser (Chrome, Safari, Firefox, etc.) 
WHEN I visit Knative.dev
THEN the homepage renders correctly
```

`Mobile`
```
GIVEN I am on my mobile phone 
WHEN I visit Knative.dev 
THEN the homepage renders correctly 
```

## Known Issues and Considerations: 
- [x] CSS on the current website needs to be optimized
- [x] Create Javascript to randomize order of logos in the "Trusted By:" section 
- [ ] Change "Trusted By" to "Companies that use Knative" 
- [ ] The homepage needs a slick Architecture diagram which shows what Serving + Eventing do, similar to https://istio.io/

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [x] New Contributors

**Comment by csantanapr** [comment]
child issues for this Epic should be created so they can be assigned to one or more individuals to work on.
In this state, folks would be hesitant to take the issue as an Epic

**Comment by csantanapr** [comment]
I think the CSS is already optimized
