### ISSUE TITLE
[EPIC] Sanity Check Serving Content

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3641]
## Description: 
We want to make sure the Serving content which lives in the Beta site (https://github.com/knative/docs/tree/mkdocs) meets a sanity-check. 

---

## Story
```
As an Eli the End User 
I want to go through the pages under the "Serving" section of the site 
And feel like some someone has done a cursory review of this section 
So that I feel the Knative site is crafted with care 
And so that I assign Knative more credibility as a result 
```

## Acceptance Criteria
`Navigation`
```
GIVEN I find my way to https://dev-knative.netlify.app/development/serving/
WHEN I look at the page 
THEN I see there is a clear navigation to the left of the content
AND all of the groupings make sense to me 
AND none of the page titles are potentially confusing 
```

`Legibility, Credibility Check`
```
GIVEN I find my way to any of the pages in the sub-directory https://dev-knative.netlify.app/development/serving/
WHEN I read through the pages 
THEN I do not find any broken links 
AND I do not find any typos
AND the way the content is organized on the page makes sense
AND there is nothing wonky looking in this section of the site 
```

## Known Issues and Considerations: 
- [x] Anywhere the user is not expected to copy and paste a code block (i.e. showing terminal output) should use the custom CSS { .bash .no-copy } as seen under "Expected Output" here: https://dev-knative.netlify.app/development/getting-started/first-service/#run-your-knative-service 
- [x] All overview pages (index.md, _index.md, README.md) should be renamed to README.md
- [x] Lots of broken links, internal and external 
- [x] Nav is a bit of a mess 

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [x] New Contributors

**Comment by omerbensaadon** [comment]
Working on this now
