### ISSUE TITLE
🛑 Add Analytics Cookie Tracking Warning (`/about-analytics-cookies`) to the Knative site

### ISSUE THREAD

**Issue by omerbensaadon** [knative/docs#3776]
## Description: 
We need to add a warning to the homepage that users who access the site to let them know we use Google Analytics to track users

---

## Story
```
As Sally the Site Visitor 
I want to know that I am being tracked by Google Analytics 
So that I am not tracked without my awareness
```

## Acceptance Criteria
- [ ] `First Site Visit`
```
GIVEN it is the first time I am accessing the Knative.dev site  
WHEN I load the homepage
THEN I see a small banner at the top of the page with the text detailed below 
AND I see an OK button
AND I see a "x" 
```

**Copy:** 
```
We use analytics and cookies to understand site traffic. Information about your use of our site is shared with Google for that purpose. <a href= https://knative.dev/about-analytics-cookies/> Learn more</a>.
```

---

- [ ] `Click OK or X`
```
GIVEN the small analytics banner is currently on my screen 
WHEN I click "OK" or "X"
THEN the banner goes away 
```

---

- [ ] `Click Learn More`
```
GIVEN the small analytics banner is currently on my screen 
WHEN I click the text "Learn more"
THEN I am taken to the page which hosts the md page below 
```
Page: https://github.com/knative/website/blob/main/content-override/en/about-analytics-cookies.md

--- 

- [ ] `Second Site Visit` 
```
GIVEN it is my second visit to knative.dev 
WHEN the homepage loads
THEN I do not see the analytics banner 
```

## Known Issues and Considerations: 
I think this JS is already done here: https://github.com/knative/website/blob/main/static/js/cookie-consent.js

Visuals are up to you, but the current look is just fine. 

## Who should probably pick up this issue? 
- [x] Existing Contributors 
- [ ] New Contributors
