### ISSUE TITLE
Calendar Invites in WORKING-GROUPS.md don't work

### ISSUE THREAD

**Issue by dprotaso** [knative/docs#422]
https://github.com/knative/docs/blob/master/contributing/WORKING-GROUPS.md

~~See: https://github.com/knative/docs/blob/master/community/WORKING-GROUPS.md~~

## Expected Behavior
- Clicking the link opens google calendar and displays the event
- The calendar event appears on the [Knative Team Calendar](https://calendar.google.com/calendar/embed?src=google.com_18un4fuh6rokqf8hmfftm5oqq4%40group.calendar.google.com)

## Actual Behavior

- [x] API
  - [x] Link opens calendar invite or Knative Team Calendar
  - [x] Meeting appears on [Knative Team Calendar](https://calendar.google.com/calendar/embed?src=google.com_18un4fuh6rokqf8hmfftm5oqq4%40group.calendar.google.com)
- [ ] Build
  - [ ] Link opens calendar invite or Knative Team Calendar
  - [ ] Meeting appears on [Knative Team Calendar](https://calendar.google.com/calendar/embed?src=google.com_18un4fuh6rokqf8hmfftm5oqq4%40group.calendar.google.com)
- [x] Documentation
  - [x] Link opens calendar invite or Knative Team Calendar
  - [x] Meeting appears on [Knative Team Calendar](https://calendar.google.com/calendar/embed?src=google.com_18un4fuh6rokqf8hmfftm5oqq4%40group.calendar.google.com)
- [x] Eventing
  - [x] Link opens calendar invite or Knative Team Calendar
  - [x] Meeting appears on [Knative Team Calendar](https://calendar.google.com/calendar/embed?src=google.com_18un4fuh6rokqf8hmfftm5oqq4%40group.calendar.google.com)
    - This actually opens a different calendar (an old elafros one)
- [x] Networking
  - [x] Link opens calendar invite or Knative Team Calendar
  - [x] Meeting appears on [Knative Team Calendar](https://calendar.google.com/calendar/embed?src=google.com_18un4fuh6rokqf8hmfftm5oqq4%40group.calendar.google.com)
- [x] Observability
  - [x] Link opens calendar invite or Knative Team Calendar
  - [x] Meeting appears on [Knative Team Calendar](https://calendar.google.com/calendar/embed?src=google.com_18un4fuh6rokqf8hmfftm5oqq4%40group.calendar.google.com)
- [x] Scaling
  - [x] Link opens calendar invite or Knative Team Calendar
  - [x] Meeting appears on [Knative Team Calendar](https://calendar.google.com/calendar/embed?src=google.com_18un4fuh6rokqf8hmfftm5oqq4%40group.calendar.google.com)
- [x] Productivity 
  - [x] Link opens calendar invite or Knative Team Calendar
  - [x] Meeting appears on [Knative Team Calendar](https://calendar.google.com/calendar/embed?src=google.com_18un4fuh6rokqf8hmfftm5oqq4%40group.calendar.google.com)

**Comment by bbrowning** [comment]
I added this to the Future Topics of the Productivity Working Group which meets shortly to see if we can get this addressed for all working groups.

**Comment by dprotaso** [comment]
Assigning working group leads to fix

/assign @ImJasonH 
/assign @josephburnett 
/assign @vaikas-google 
/assign @mattmoor

**Comment by dprotaso** [comment]
The remaining issue here is the Build WG

@ImJasonH Can you get the meeting onto this calendar and update the link in [WORKING-GROUPS.md](https://github.com/knative/docs/blob/master/community/WORKING-GROUPS.md)

**Comment by samodell** [comment]
@ImJasonH  Can you add the Build meeting to the shared Knative calendar?

**Comment by aslom** [comment]
The link in this issue does not work - it should be with "contributing" not "community"
https://github.com/knative/docs/blob/master/contributing/WORKING-GROUPS.md
https://knative.dev/contributing/working-groups/
https://github.com/knative/docs/edit/master/contributing/WORKING-GROUPS.md

**Comment by ImJasonH** [comment]
Sorry I've missed so many of these pings! I don't have permission to edit the Knative calendar, someone else will have to do it, or add me to the ACL.

**Comment by vaikas-google** [comment]
@RichieEscarez is the Eventing still broken? I tried to bring it up and it seemed right to me. If not, @mogar1980 could you modify the event because it's owned by you.

**Comment by mogar1980** [comment]
I think Eventing is working. I see both the recurring WG and one-off meetings that have been added in the last few months

**Comment by RichieEscarez** [comment]
Hi @ImJasonH and @mattmoor, the only pending item here is to fix the link to the Build calendar.

Issues:
1. Currently Build opens a one-off copy: https://calendar.google.com/event?action=TEMPLATE&tmeid=MTBkb3MwYnVrbDd0djE0a2kzcmpmbjZndm9fMjAxODA5MTJUMTcwMDAwWiBqYXNvbmhhbGxAZ29vZ2xlLmNvbQ&tmsrc=jasonhall%40google.com&scp=ALL
1. The reoccurring build meeting are not listed in the team calendar

Action items:
1. Update the link in the [WORKING-GROUPS.md](https://github.com/knative/docs/blob/master/contributing/WORKING-GROUPS.md) to point to the team calendar

   For example: Eventing:
https://calendar.google.com/calendar/embed?src=google.com_18un4fuh6rokqf8hmfftm5oqq4%40group.calendar.google.com

2. Add Build meetings to the that team calendar

**Comment by RichieEscarez** [comment]
@rgregg or @argent who has ACL privileges to Jason to the team calendar?

**Comment by dprotaso** [comment]
the real argent @evankanderson

**Comment by evankanderson** [comment]
For some reason, Jason was the only WG lead (AFAICT) that had not been invited to the shared calendar. Fixed.
