### ISSUE TITLE
Knative Serving: match directory structure to site structure

### ISSUE THREAD

**Issue by snneji** [knative/docs#4376]
Start this issue after #4296 is delivered.

### Context 
During the Card Sort, many folks grouped the Serving documentation under a "Knative Serving" section, see https://miro.com/app/board/o9J_l1Iv2e4=/. Taking this into account, the site navigation was updated in PR #4382.

Now, the files in the [`/docs/serving`](https://github.com/knative/docs/tree/main/docs/serving) directory need to be updated to match the new site navigation.

### Tasks
- [x] Move files into the `/docs/serving` directory to match the Knative Serving section in the site structure 
- [x] Fix existing links to match the new file locations
- [x] Add redirects for the files that have moved
