### ISSUE TITLE
Knative Eventing: match directory structure to site structure

### ISSUE THREAD

**Issue by snneji** [knative/docs#4377]
Start this issue after #4296 is delivered.

### Context 
During the Card Sort, many folks grouped the Serving documentation under a "Knative Evnting" section, see https://miro.com/app/board/o9J_l1Iv2e4=/. Taking this into account, the site navigation was updated in PR #4382.

Now, the files in the [`/docs/eventing`](https://github.com/knative/docs/tree/main/docs/eventing) directory need to be updated to match the new site navigation.

### Tasks
- [x] Move Eventing files from the `/docs/admin` and `/docs/developer` directories into `/docs/eventing` to match the Knative Eventing section in the site structure 
- [x] Fix existing links to match the new file locations
- [x] Add redirects for the files that have moved
