### ISSUE TITLE
Update links to community guide

### ISSUE THREAD

**Issue by snneji** [knative/docs#4576]
## Context

Community guide has moved to MkDocs. We need to reduce confusion around contributing and community links on the site.

## Tasks

- [x] Update the contribute call to action on home page to https://knative.dev/docs/community/contributing/ 
- [x] Change "Join the Community" to "Community" in the menu
- [x] Update Community overview page name
- [x] Redirect away from old docs contributor guide. `help/contributor/*: https://github.com/knative/docs/blob/main/contribute-to-docs/README.md`
- [ ] Cherry pick back to 0.25
