### ISSUE TITLE
Knative 1.3 release notes blog post

### ISSUE THREAD

**Issue by snneji** [knative/docs#4790]
## Tasks

1. After each component has released, consolidate all release notes into a blog post similar to the [Knative 1.2 blog post](https://knative.dev/blog/releases/announcing-knative-v1-2-release/). Use the [template](https://github.com/knative/docs/blob/main/blog/docs/releases/_template-announcing-knative-v1-X-release.txt) to format the blog post correctly.
2. Add the new blog page to `blog/config/nav.yml`
3. Update the "featured posts" section of `blog/docs/index.md` with the new release. 

## Resources

Add the following release notes to the post:
- [x] https://github.com/knative/serving/releases/tag/knative-v1.3.0
- [x] https://github.com/knative/eventing/releases/tag/knative-v1.3.0
- [x] https://github.com/knative-sandbox/eventing-kafka-broker/releases/tag/knative-v1.3.0
- [x] https://github.com/knative-sandbox/eventing-rabbitmq/releases/tag/knative-v1.3.0
- [x] https://github.com/knative/client/blob/main/CHANGELOG.adoc#v130-2022-03-08
- [x] https://github.com/knative/operator/releases/tag/knative-v1.3.0
