### ISSUE TITLE
 Knative 1.4 release notes blog post

### ISSUE THREAD

**Issue by snneji** [knative/docs#4902]
## Tasks

After Knative 1.4 release day (April 19, 2022):
1. After each component has released, consolidate all release notes into a blog post similar to the [Knative 1.2 blog post](https://knative.dev/blog/releases/announcing-knative-v1-2-release/). Use the [template](https://github.com/knative/docs/blob/main/blog/docs/releases/_template-announcing-knative-v1-X-release.txt) to format the blog post correctly.
2. Add the new blog page to `blog/config/nav.yml`
3. Update the "featured posts" section of `blog/docs/index.md` with the new release. 

## Resources

Add the following release notes to the post:
- [ ] https://github.com/knative/serving/releases/tag/knative-v1.4.0
- [ ] https://github.com/knative/eventing/releases/tag/knative-v1.4.0
- [ ] https://github.com/knative-sandbox/eventing-kafka-broker/releases/tag/knative-v1.4.0
- [ ] https://github.com/knative-sandbox/eventing-rabbitmq/releases/tag/knative-v1.4.0
- [ ] https://github.com/knative/client/blob/main/CHANGELOG.adoc#v140-2022-04-19
- [ ] https://github.com/knative/operator/releases/tag/knative-v1.4.0

**Comment by csantanapr** [comment]
@xtreme-sameer-vohra would be able to do this or find someone new that wants to get a contribution

**Comment by xtreme-sameer-vohra** [comment]
cc @nader-ziada who volunteered as the release lead. 
Depending on how it goes, one idea was for Nader to update the release process and make it so that it would be done by the release leads. WDYT ?

**Comment by csantanapr** [comment]
@xtreme-sameer-vohra that would be a great idea for the release lead to do the release notes blog. 

What do you think @nader-ziada can you do it for 1.4?

**Comment by csantanapr** [comment]
This is also beneficial as global release notes we need all the release notes from the individual components cli, operator, eventing, serving, etc..

So the release is not done done until the release blog post is published.

**Comment by nader-ziada** [comment]
yeah, will work on it

**Comment by nader-ziada** [comment]
still don't have release notes for cli and waiting for operator to be released as well
