### ISSUE TITLE
Release docs for Knative v1.3

### ISSUE THREAD

**Issue by snneji** [knative/docs#4903]
## Task

Cut a release for 1.4. For instructions, see the [docs release process](https://github.com/knative/docs/blob/main/contribute-to-docs/docs-release-process.md).

The remaining versions in the script `hack/build.sh` should be: 1.4, 1.3, 1.2, 1.1

## Dependencies

Wait for the following components to be released:
- [x] [Serving 1.4](https://github.com/knative/serving/releases/tag/knative-v1.4.0)
- [x] [Eventing 1.4](https://github.com/knative/eventing/releases/tag/knative-v1.4.0)
- [x] [Kn CLI 1.4](https://github.com/knative/client/releases/tag/knative-v1.4.0)
- [x] [Operator 1.4](https://github.com/knative/operator/releases/tag/knative-v1.4.0)
- [x] Kn Plugins 1.4 and Homebrew released (release PR merged in [this repo](https://github.com/knative-sandbox/homebrew-kn-plugins))

**Comment by nainaz** [comment]
PR : https://github.com/knative/docs/pull/4935

**Comment by snneji** [comment]
PR submitted
