### ISSUE TITLE
Fix tab formatting in code-samples folder

### ISSUE THREAD

**Issue by snneji** [knative/docs#4922]
## Background
The files in `code-samples` folder are no longer viewable on the website, only in GitHub. However, this has caused broken formatting because tabbed elements are not available in GitHub markdown. 

## Task
Remove the tabbed formatting, for example `=== "yaml"`, in the files in the `code-samples` folder. Make sure that if the tabbed formatting is under a step, you indent your new formatting within each step.

Files that have this issue:
- [ ] [./code-samples/serving/cloudevents/cloudevents-nodejs/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/cloudevents/cloudevents-nodejs/README.md)
- [ ] [./code-samples/serving/cloudevents/cloudevents-rust/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/cloudevents/cloudevents-rust/README.md)
- [ ] [./code-samples/serving/cloudevents/cloudevents-go/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/cloudevents/cloudevents-go/README.md)
- [ ] [./code-samples/serving/cloudevents/cloudevents-vertx/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/cloudevents/cloudevents-vertx/README.md)
- [ ] [./code-samples/serving/cloudevents/cloudevents-spring/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/cloudevents/cloudevents-spring/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-ruby/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-ruby/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-shell/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-shell/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-java-spring/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-java-spring/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-python/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-python/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-java-spark/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-java-spark/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-go/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-go/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-php/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-php/README.md)
- [ ] [./code-samples/serving/hello-world/helloworld-scala/README.md](https://github.com/knative/docs/tree/main/code-samples/serving/hello-world/helloworld-scala/README.md)

**Comment by snneji** [comment]
@abrennan89 The original reason why we moved the samples is mainly to make it easier for devs to clone the repo and have the whole sample, including instructions and accompanying YAML and other files, in one place. We got feedback from quite a few people saying they preferred to use the samples from GitHub rather than using them from the docs. 

We also felt that if the samples are on the site, it would be our (Docs WG) responsibility to make sure they are up to date.  We were considering moving the samples out of the docs repo entirely so that we would not be responsible for keeping them updated. However, we couldn't find anyone else who wanted the be responsible for updating the samples.

We discussed again in WG meeting today (August 30 2022) and keeping the samples in GitHub with links in the docs was again the consensus.
