### ISSUE TITLE
[EPIC] Additional content strategy work required to answer longstanding questions about Knative docs

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5054]
Braindump of current requirements and priorities. We will add separate github issues as these become actionable, so that they can be assigned and worked on as part of the docs roadmap.

- [x] Create better conceptual information in the docs so that it's clear what different terms mean on a case by case basis, either similarly to Kubernetes documents concepts (https://kubernetes.io/docs/concepts/) or just by improving conceptual info throughout the docs. (Follows up on https://github.com/knative/docs/issues/170)
- [ ] We will open an additional issue to create a page named something like Adopters (? name needs more discussion probably) that provides info about who is using Knative, case studies, things like managed cloud offerings (since these are not a community thing but might be provided by partners / companies using Knative in products or on their platforms) (Follow up from https://github.com/knative/docs/issues/4668)
- [ ] Istio vs Kourier vs other options, what is required, what isn't, and why users would use one over the other - this should be addressed adequately in the core docs so that it's not a question that's being asked all the time (Follow up from https://github.com/knative/docs/issues/4668)
- [x] Figure out what options are for landing pages / overviews with mkdocs
- [ ] Follow this up with an audit for the current state of overview pages and create issues to batch update these and make the structure consistent across topics, depending on what structure we end up going with
- [ ] Once we've decided about overview pages, decide the fate of https://github.com/knative/docs/issues/4305
