### ISSUE TITLE
Broker documentation needs cleanup

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5105]
## Expected Behavior

There's a clear place to find documentation on configuring brokers for the cluster or for a namespace.

## Actual Behavior

- Broker documentation is scattered and hard to find throughout multiple places in docs.
- Broker documentation is divided by Operator config vs ConfigMap and it's not clear what the differences are or which a user would use in different setups.
- There is not enough documentation for non-default broker types, e.g. Kafka, other 3rd party brokers.

## Steps to Reproduce the Problem

Conceptual broker info
- https://knative.dev/docs/eventing/broker/
- https://knative.dev/docs/getting-started/first-broker/

Developer broker docs
- Create default broker https://knative.dev/docs/eventing/broker/create-mtbroker/
- https://knative.dev/docs/eventing/broker/rabbitmq-broker/
- https://knative.dev/docs/eventing/broker/kafka-broker/
- https://knative.dev/docs/eventing/flows/sequence/sequence-with-broker-trigger/
- https://knative.dev/docs/eventing/observability/metrics/eventing-metrics/#broker-filter
- https://knative.dev/docs/eventing/event-delivery/#configuring-broker-event-delivery
- https://knative.dev/docs/eventing/sugar/#automatic-broker-creation
- https://knative.dev/docs/eventing/flows/sequence/#using-sequence-with-brokertrigger-model
- https://knative.dev/docs/eventing/sources/kafka-source/#connecting-to-a-tls-enabled-kafka-broker
- https://knative.dev/docs/eventing/accessing-traces/
- https://knative.dev/docs/eventing/event-registry/
- https://knative.dev/docs/getting-started/first-trigger/
- https://knative.dev/docs/eventing/sinks/kafka-sink/#installation
- https://knative.dev/docs/eventing/configuration/sugar-configuration/

Operator broker docs
- https://knative.dev/docs/install/operator/configuring-eventing-cr/#configuring-the-default-broker-class
- https://knative.dev/docs/install/operator/configuring-eventing-cr/#setting-the-default-channel-for-the-broker
- 

Broker config (non-Operator)
- https://knative.dev/docs/eventing/configuration/broker-configuration/
- https://knative.dev/docs/eventing/broker/example-mtbroker/
- https://knative.dev/docs/eventing/sugar/#automatic-broker-creation
- https://knative.dev/docs/install/yaml-install/eventing/install-eventing-with-yaml/#optional-install-a-broker-layer
- https://knative.dev/docs/install/uninstall/#uninstalling-an-optional-broker-eventing-layer

Dev / other repo docs
- Broker spec https://github.com/knative/specs/blob/main/specs/eventing/overview.md#broker
- https://github.com/knative/specs/blob/main/specs/eventing/control-plane.md#broker-lifecycle

## Fix

- [ ] Consolidate broker docs
- [ ] Create full, end to end user stories for admins and developers for each broker setup (more like tutorials)
- [ ] Create snippets as required for conceptual content reuse
- [ ] TBA
