### ISSUE TITLE
[WIP] [EPIC] General documentation cleanup tasks

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5116]
During reviews of the site I have noticed the following issues that could be cleaned up. Braindump list as follows:

- [x] Move [concepts](https://knative.dev/docs/reference/concepts/duck-typing/) to own top level section so that it's findable
- [x] Figure out other concepts that can be documented in that section
- [ ] Move https://knative.dev/development/serving/knative-kubernetes-services/ to https://knative.dev/development/install/yaml-install/serving/serving-installation-files/ - update section to discuss not just files, but what is installed or created by install files by default. Maybe move Kubernetes Services info to snippet and include in any Concept sections also.
- [ ] Move https://knative.dev/development/serving/accessing-traces/ to Observability section.
- [ ] Create Security section and move https://knative.dev/development/serving/istio-authorization/ there.
- [ ] Move https://knative.dev/development/serving/webhook-customizations/ - does this belong in Upgrading or Troubleshooting?
- [ ] Move https://knative.dev/development/serving/using-a-tls-cert/ to new Security section.
- [ ] Move https://knative.dev/development/serving/using-auto-tls/ to new Security section.
- [ ] https://knative.dev/development/serving/setting-up-custom-ingress-gateway/ - why do we use Istio ingress gateway by default? What if someone uses a different networking layer; does this step to change the gateway then become mandatory?
- [ ] Move https://knative.dev/development/serving/autoscaling/autoscale-go/ either to the rest of the samples or properly integrate in autoscaling docs.
- [ ] Replace all config options that are "per revision" with "per service" - currently this is confusing, they're set in the Service object.
- [ ] TBA

I'll split these into proper issues or fix them later.
