### ISSUE TITLE
[EPIC] Consistent diagrams

### ISSUE THREAD

**Issue by abrennan89** [knative/docs#5129]
## Expected Behavior

Diagrams should be available for all major Knative concepts and workflows, and should be consistent in the use of color, icons, and creation tools.

## Actual Behavior

Many diagrams don't exist; those that do are inconsistent and often messy or out of date. There are no guidelines for creating diagrams.

## Tasks (to be split into issues)

- [ ] Decide on a tool for diagrams
- [ ] Decide on an icon set for diagrams and create a key for icons
- [ ] Create a list of diagrams missing from the docs
- [ ] Create new diagrams to fill gaps in documentation
