### ISSUE TITLE
Release docs for Knative v1.7

### ISSUE THREAD

**Issue by snneji** [knative/docs#5181]
## Task

Cut a release for 1.7 after release day (August 23, 2022). For instructions, see the [docs release process](https://github.com/knative/docs/blob/main/contribute-to-docs/docs-release-process.md).

The remaining versions in the script `hack/build.sh` should be: 1.7, 1.6, 1.5, 1.4

## Dependencies

Wait for the following components to be released:
- [x] [Serving 1.7](https://github.com/knative/serving/releases/tag/knative-v1.7.0)
- [x] [Eventing 1.7](https://github.com/knative/eventing/releases/tag/knative-v1.7.0)
- [x] [Kn CLI 1.7](https://github.com/knative/client/releases/tag/knative-v1.7.0)
- [x] [Operator 1.7](https://github.com/knative/operator/releases/tag/knative-v1.7.0)
- [x] Kn Plugins 1.7 and Homebrew released (release PR merged in [this repo](https://github.com/knative-sandbox/homebrew-kn-plugins))
