### ISSUE TITLE
Create a Functions section 

### ISSUE THREAD

**Issue by lance** [knative/docs#5265]
**Describe the change you'd like to see**

Evan in https://github.com/knative/docs/pull/5243#discussion_r989327583

We'll need to add more content here (fine in a subsequent PR):

- [x] What is it / how does it work?
- [ ] How do I use it / what's the intended workflow?
  - [ ] Create
  - [ ] Iterate
  - [ ] Integrate in build system
  - [ ] Update buildpack / other maintenance needed?
- [ ] What's a language pack / how can I get more of them?
  - [ ] Language pack inventory page
  - [ ] Writing your own language pack

**Comment by lance** [comment]
No I mean language pack. https://github.com/knative/func/blob/main/docs/language-pack-providers/language-pack-contract.md

It's how companies and vendors extend Functions

**Comment by abrennan89** [comment]
Moved advanced questions about lang packs to separate issue.

**Comment by abrennan89** [comment]
@lance per Evan's original comment, is there enough info about buildpacks yet to warrant opening a follow up issue for advanced docs about that?
