### ISSUE TITLE
Release docs for Knative v1.8

### ISSUE THREAD

**Issue by nak3** [knative/docs#5289]
## Task

Cut a release for 1.8 after release day. For instructions, see the [docs release process](https://github.com/knative/release/blob/main/PROCEDURES.md#releasing-a-new-version-of-the-knative-documentation).

The remaining versions in the script `hack/build.sh` should be: 1.8 1.7, 1.6, 1.5 (Please fix me if it is wrong. I just decided it from https://github.com/knative/docs/issues/5181)

## Dependencies

Wait for the following components to be released:
- [x] [Serving 1.8](https://github.com/knative/serving/releases/tag/knative-v1.8.0)
- [x] [Eventing 1.8](https://github.com/knative/eventing/releases/tag/knative-v1.8.0)
- [x] [Kn CLI 1.8](https://github.com/knative/client/releases/tag/knative-v1.8.0)
- [x] [Operator 1.8](https://github.com/knative/operator/releases/tag/knative-v1.8.0)
- [x] Kn Plugins 1.8 and Homebrew released (release PR merged in [this repo](https://github.com/knative-sandbox/homebrew-kn-plugins)) 
 - https://github.com/knative-sandbox/homebrew-kn-plugins/pull/118
 - https://github.com/knative/homebrew-client/pull/81
