### ISSUE TITLE
Clean up the code samples that aren't helloworld.

### ISSUE THREAD

**Issue by rgregg** [knative/docs#59]
Here's the samples and who's working on them:

Samples
- [x] autoscale-go @josephburnett
- [x] build-privat-repo-go @samodell PR is #213
- [x] buildpack-app-dotnet @samodell PR is #222
- [x] buildpack-function-nodejs @samodell #222 
- [x] gitwebhook-go rgregg PR is #215 
- [ ] grpc-ping-go @averikitsch
- [x] knative-routing-go
- [x] rest-api-go @averikitsch PR is #225
- [x] source-to-url-go
- [x] telemetry-go
- [x] thumbnailer-go @samodell PR is #231
